import { MemoryEvent } from './types';

export const memoryEvents: MemoryEvent[] = [
  {
    id: '1',
    tags: ['日常', '里程碑'],
    title: 'First Date',
    date: 'June 1, 2021',
    shortDescription: 'Where it all began.',
    longDescription: 'Our first date at this cozy little cafe. We talked for hours, completely losing track of time. It felt like magic, the start of something truly special.',
    location: { name: 'The Corner Cafe, Paris', coords: [48.8566, 2.3522] },
    imageUrls: ['https://picsum.photos/800/600?random=1'],
    audioUrl: 'https://aistudiocdn.com/samples/music.mp3',
  },
  {
    id: '2',
    tags: ['旅行'],
    title: 'Kyoto Cherry Blossoms',
    date: 'April 5, 2022',
    shortDescription: 'A walk to remember.',
    longDescription: 'Walking hand-in-hand under the cherry blossoms in Kyoto was a dream come true. The air was filled with the sweet scent of sakura, and every moment felt like a scene from a movie.',
    location: { name: 'Philosopher\'s Path, Kyoto', coords: [35.021, 135.79] },
    imageUrls: ['https://picsum.photos/800/600?random=2', 'https://picsum.photos/800/600?random=11', 'https://picsum.photos/800/600?random=12'],
  },
  {
    id: '3',
    tags: ['日常', '自然'],
    title: 'Our Favorite Park',
    date: 'August 15, 2022',
    shortDescription: 'Simple, happy moments.',
    longDescription: 'Our go-to spot for weekend picnics and lazy afternoon strolls. So many simple, happy memories were made here, just enjoying each other\'s company and the beauty of nature.',
    location: { name: 'Central Park, New York', coords: [40.785091, -73.968285] },
    imageUrls: ['https://picsum.photos/800/600?random=3'],
  },
  {
    id: '4',
    tags: ['旅行'],
    title: 'Roman Holiday',
    date: 'September 10, 2022',
    shortDescription: 'Exploring ancient ruins.',
    longDescription: 'We felt like characters in an old film while exploring the Colosseum. We tossed a coin in the Trevi Fountain, wishing for our eternal love and many more adventures together.',
    location: { name: 'Colosseum, Rome', coords: [41.8902, 12.4922] },
    imageUrls: ['https://picsum.photos/800/600?random=4', 'https://picsum.photos/800/600?random=13'],
  },
  {
    id: '5',
    tags: ['旅行', '纪念日', '里程碑'],
    title: 'The Proposal',
    date: 'December 24, 2022',
    shortDescription: 'A night of a thousand stars.',
    longDescription: 'Under the magical glow of the Northern Lights, you asked, and I said yes. My heart was overflowing with joy. It was the easiest decision I\'ve ever made.',
    location: { name: 'Tromsø, Norway', coords: [69.6492, 18.9553] },
    imageUrls: ['https://media.giphy.com/media/3o7TKVmIIrSA4Y26ic/giphy.gif'],
    audioUrl: 'https://aistudiocdn.com/samples/music.mp3',
  },
   {
    id: '6',
    tags: ['旅行'],
    title: 'Sydney Opera House',
    date: 'February 20, 2023',
    shortDescription: 'Down Under Adventure.',
    longDescription: 'Seeing the iconic Sydney Opera House was breathtaking. We enjoyed the vibrant city life and beautiful beaches, making unforgettable memories on the other side of the world.',
    location: { name: 'Sydney, Australia', coords: [-33.8568, 151.2153] },
    imageUrls: ['https://media.giphy.com/media/l2YSgsunrP27ddQje/giphy.gif'],
  },
  {
    id: '7',
    tags: ['愿望'],
    title: 'Future Honeymoon',
    date: 'Future',
    shortDescription: 'Dreaming of our next chapter.',
    longDescription: 'We dream of watching the sunset from a whitewashed villa, celebrating the beginning of our forever. This is the next big adventure on our list!',
    location: { name: 'Santorini, Greece', coords: [36.3932, 25.4615] },
    imageUrls: ['https://picsum.photos/800/600?random=7'],
  },
  {
    id: '8',
    tags: ['旅行', '自然'],
    title: 'Santorini Sunset',
    date: 'July 16, 2023',
    shortDescription: 'Witnessing the magic.',
    longDescription: 'The world seemed to pause as we watched the sun dip below the horizon, painting the sky with hues of orange and pink. Holding your hand in that moment, I knew I had everything I ever wanted.',
    location: { name: 'Oia, Santorini', coords: [36.4619, 25.3753] },
    imageUrls: ['https://picsum.photos/800/600?random=8', 'https://picsum.photos/800/600?random=14', 'https://picsum.photos/800/600?random=15', 'https://picsum.photos/800/600?random=16'],
  },
  {
    id: '9',
    tags: ['日常', '美食'],
    title: 'Morning Croissants',
    date: 'June 2, 2021',
    shortDescription: 'A perfect Parisian morning.',
    longDescription: 'Waking up to the smell of fresh pastries and sharing a croissant with you at a small bakery near our hotel. The simple moments are often the most romantic.',
    location: { name: 'A small bakery, Paris', coords: [48.8566, 2.3522] },
    imageUrls: ['https://picsum.photos/800/600?random=9'],
  },
];
